name: Jekyll site CI

on:
  push:
    branches: [ "rama1" ]    # Cambiar "main" por "rama1"
  pull_request:
    branches: [ "rama1" ]    # Cambiar "main" por "rama1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

